### ISSUE TITLE
should add prefix on metrics

### ISSUE THREAD

**Issue by shackerd** [shackerd/freebox-exporter-rs#10]
>Hi, 
>...
>Also maybe add some unique prefix to the identifier exported by prometheus - something like fbx_system_fan_rpm instead of system_fan ?

_Originally posted by @ottobaer in https://github.com/shackerd/freebox-exporter-rs/issues/8#issuecomment-2258637665_

**Comment by shackerd** [comment]
If I add prefix to `system_fan` I must add this prefix also to the rest of the metrics for consistency purposes. 

If I'm right, `system` prefix violates good practices or may be confused with others?

**Comment by ottobaer** [comment]
Hi, 

Yes I meant to say add a prefix for all the metrics exported. 

https://prometheus.io/docs/practices/naming/

```

..should have a (single-word) application prefix relevant to the domain the metric belongs to. The prefix is sometimes referred to as namespace by client libraries. For metrics specific to an application, the prefix is usually the application name itself. Sometimes, however, metrics are more generic, like standardized metrics exported by client libraries. Examples:

    prometheus_notifications_total (specific to the Prometheus server)
    process_cpu_seconds_total (exported by many client libraries)
    http_request_duration_seconds (for all HTTP requests)

```

**Comment by shackerd** [comment]
Sounds legit, I will add a configurable prefix in `config.toml` then.
