### ISSUE TITLE
Bridge mode (freebox delta v8) 

### ISSUE THREAD

**Issue by ottobaer** [shackerd/freebox-exporter-rs#2]
Hi, 

I have got a freebox delta v8 in bridge mode. I assume the exporter tries to get my public IP  and fails because it can't be reached externally/internally. 

```


    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/freebox-exporter-rs register`
thread 'main' panicked at src/main.rs:59:19:
reqwest::Error {
    kind: Request,
    url: Url {
        scheme: "https",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Domain(
                "machintruc.fbxos.fr",
            ),
        ),
        port: Some(
            20888,
        ),
        path: "/api/v4/login/authorize",
        query: None,
        fragment: None,
    },
    source: hyper_util::client::legacy::Error(
        Connect,
        ConnectError(
            "tcp connect error",
            Os {
                code: 101,
                kind: NetworkUnreachable,
                message: "Network is unreachable",
            },
        ),
    ),
}
```

As far as I understand it I can still use the API in bridge mode. <- I might be wrong here though. 

For example registering an application with curl on my freebox in bridge mode still works: 

`
curl -X POST -H "content-Type: application/json" -d '{"app_id": "fr.freebox.testapp", "app_name": "Test App", "app_version": "0.0.1", "device_name": "PC-test-device"}' http://mafreebox.freebox.fr/api/v11/login/authorize/`
 
I can query the result of the registration, so in my understanding that means I would be able to query the box and get the results. 

Thank You,

**Comment by shackerd** [comment]
Hello @ottobaer, thanks for testing. indeed api seems to have a different behavior in `bridge mode`. The application tries to resolve Freebox hostname on the `api_version` endpoint, it seems this host (example.fbxos.fr) cannot be reachable in your case. Can you give me the output of the following command ? (don't forget to obsfucate your sensitive data such as hostname prefix as you did before). 

``` bash curl http://mafreebox.freebox.fr/api_version
``` 

I plan to test mDNS instead of this http hop as the documentation advises. However, it would be more simple to use the `mafreebox.freebox.fr` host on each call, but actually I can't be sure if it works for all cases. This would mean the discovery process is useless.

**Comment by ottobaer** [comment]
I think mafreebox.freebox.fr should always work internally but not externally, that's why I can use the api with curl for example on mafreebox.freebox.fr. 

Here is the output of `api_version`

```

{"box_model_name":"Freebox v8 `(r1)","api_base_url":"\/ api\/","https_port":20888,"device_name":"antbear","https_available":true,"box_model":"fbxgw8-r1","api_domain":"machintruc.fbxos.fr","uid":"123456","api_version":"11.1","device_type":"FreeboxServer8,1"}%`  

```

I don't know if mDNS changes anything here, because I guess mDNS will also just give the `api_domain`, something like` *.fbxos.fr ` if it is even possible to get the box to reply in bridge mode ?

**Comment by shackerd** [comment]
This is my though too, but the only way to determine if remote access is enabled is to call the `/api/v4/connection/config` endpoint. Unfortunately this endpoint does not allow anonymous access. c.f.: [ConnectionConfiguration](https://dev.freebox.fr/sdk/os/connection/#ConnectionConfiguration) IMO the application should stay in private network, then discovery API wont be a problem anymore.

**Comment by shackerd** [comment]
I added a setting in `conf.toml` to enable usage of discovery (default: `false`). If not set the application will use `mafreebox.freebox.fr`

**Comment by shackerd** [comment]
I also tested **mDNS**, as expected, related infos are the **same** as the `api_version` endpoint entries. 

You may check these by running following command: 

``` bash 
avahi-browse _fbx-api._tcp -r
```

> Remark to get mDNS working behind another router you must replicate theses multicast packets on your network areas.

I think I found the reason behind `bridge mode` issue, I checked out DNS entries for both `mafreebox.freebox.fr` and `********.fbxos.fr`. 
Here the results : 
* mafreebox.freebox.fr resolves to a public IP like 212.XXX.XXX.XXX
* ********.fbxos.fr resolves to your public IP like 88.XXX.XXX.XXX

My conclusion is : If you are using `********.fbxos.fr` in `bridge mode` which resolves to your public IP, no device will handle the API and then HTTP calls **will not work**

**Comment by ottobaer** [comment]
I just tested your changes and it works as expected :). 

I can register the exporter on the freebox and I can get the metrics from prometheus. 

```

cargo run serve
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/freebox-exporter-rs serve`
using https://mafreebox.freebox.fr/api/
Some(
    Permissions {
        connection: false,
        settings: false,
        contacts: true,
        calls: true,
        explorer: true,
        downloader: true,
        parental: false,
        pvr: true,
    },
)

```

```
# HELP connection_bandwidth_down connection_bandwidth_down
# TYPE connection_bandwidth_down gauge
connection_bandwidth_down 5000000000
# HELP connection_bandwidth_up connection_bandwidth_up
# TYPE connection_bandwidth_up gauge
connection_bandwidth_up 700000000
# HELP connection_bytes_down connection_bytes_down
# TYPE connection_bytes_down gauge
connection_bytes_down 107040967216
# HELP connection_bytes_up connection_bytes_up
# TYPE connection_bytes_up gauge
connection_bytes_up 25692301864
```

**Comment by shackerd** [comment]
Great news ! 😊
