### ISSUE TITLE
Cross build declare openssl 

### ISSUE THREAD

**Issue by ottobaer** [shackerd/freebox-exporter-rs#8]
Hi, 

First, thanks a lot for the exporter, its really nice to finally be able to monitor my freebox in Grafana :-). 

I used cross to build arm64 binaries since I run the exporter on an orangepi. 

I needed to add the following to Cargo.toml for it to build: 

`openssl = { version = "0.10.64", features = ["vendored"] }`

Maybe needs to be updated to 0.10.66 now? 

I have not enough knowledge of go and cross to say if that is the right way to do it, but maybe you could add something  in Cargo.toml so cross compiling works. 

thank you,

**Comment by shackerd** [comment]
Hey @ottobaer, thanks for testing and providing feedbacks! I'm glad this is running well on orangepi! :smile: 
So, `openssl` is an indirect dependency, this may indeed affect building process. I created a PR #9  for this issue.

BTW, if you want to share your Grafana board or whatever, feel free to do so! (In fact, I'm not that good in setting up Grafana boards :smiling_face_with_tear:

**Comment by ottobaer** [comment]
Hi, 

Thanks for adding the dependency! 

I should be able to come up with some dashboard tomorrow. I think the best way to do that would be to make some reference dashboard with a few variables. 

Also maybe add some unique prefix to the identifier exported by prometheus - something like fbx_system_fan_rpm instead of system_fan ?

**Comment by shackerd** [comment]
It's up to you, no need to hurry for Grafana board(s), do it as your ease :wink: 

I created a new issue #10 for metrics prefix, I closing this one.
